### ISSUE TITLE
Some small questions about using

### ISSUE THREAD

**Issue by frankyugit** [robertsawko/OpenPBE#15]
Dear Robert,

I'm a PHD student of KIT, Germany. Thanks to share your solver, that is really pretty helpful to my work.
For the PBEFoam solver, I have got some small questions about using.
1st PBEFoam is an independent solver, or a lib together with twoPhaseEulerFoam. For the second situation. How can we set up some coefficients for QMOM part.
2nd Where is the folder "testing/twoPhaseEulerFoam"
3rd Where can we get the test cases? Is the folder "test" the one for this, then how would we install these test cases?

Thanks a lot ^_^

**Comment by robertsawko** [comment]
Hi Frank,

Thanks for getting interested in this project. You may have noticed that it is really in active development. I am keeping in open in case people are willing and have the time to contribute. The code has a number of issues.
1. PBEFoam is a separate solver. If you want to use the library together with twoPhaseEulerFoam you must have
   `
   libs ("libPBE.so");
   `
   in your `controlDict`. 
2. That was a mistake in the README. I just corrected it. See in `tests/validation` 
3. Test cases don't need installation. Simply copy them to your run directory. OpenFOAM supports a default a run directory which you will see by typing `echo $FOAM_RUN`. If you don't have that directory simply use `mkdir -p $FOAM_RUN`. There's also an alias `run` which automatically cds you there. Just copy the cases there and start running.

Also don't feel you need to use that, although it's quite convenient, especially `run` alias. It keeps your library of cases clean.

I am closing this. Consider joining us on Gitter channel for more questions of this type. Consider forking the project and helping us develop it. QMOM functionality needs testing.

Also checkout [OpenQBMM](https://www.openqbmm.org/) project. It may be closer to what you're looking for.

**Comment by frankyugit** [comment]
Hello Robert,

Thanks to your reply, which is really helpful.
This project is highly related to my work now, so I'm pretty interested. I
have already joined in the Gitter group. Hope to talk with guys more.
For the using part, I still get some questions.
Thanks to correct the README, however, in "tests/validation", still no
folder named "twoPhaseEulerFoam", only something like galinat and simmons_
and_azzopardi.
I have tried both cases to do testing, however, maybe still something wrong
in this part.
For the simmons_ and_azzopardi case, everytime, I try the python script
"setupCases.py", always a error happens with "_SyntaxError: Non-ASCII
character '\xc4' in file
/home/local/KIT/vx3046/OpenPBE/tests/validation/simmons_and_azzopardi/symcalc.py
on line 6, but no encoding declared; see
http://www.python.org/peps/pep-0263.html
http://www.python.org/peps/pep-0263.html for details_"
For the galinat case, I can successfully run the python script, then
several similar cases will be generated. I just tried one of them like
"NC30". The blockMesh runs quite well, however, when I tried to run the
solver

_PBEFoam, seems error happens, like--> FOAM FATAL IO ERROR: keyword
relaxation is undefined in dictionary
"/home/local/KIT/vx3046/OpenPBE/tests/validation/galinat/template/constant/phaseProperties.oil.PBEDiameterCoeffs.MOCCoeffs"file:
/home/local/KIT/vx3046/OpenPBE/tests/validation/galinat/template/constant/phaseProperties.oil.PBEDiameterCoeffs.MOCCoeffs
from line 28 to line 30.    From function dictionary::lookupEntry(const
word&, bool, bool) const    in file db/dictionary/dictionary.C at line
442.FOAM exiting_
Bases on the information from shell, maybe we the entrance "relaxation"
needs to be added to the phaseProperties. So should we add the "relaxtion"
to the file by ourselves? What is the meaning of "relaxation" here? Any
recommended setting value for it?

2016-06-01 19:31 GMT+02:00 Robert Sawko notifications@github.com:

**Comment by robertsawko** [comment]
Frank, can I ask you to submit errors like this as separate issues?

You are looking in the right place. There's no twoPhaseEulerFoam but experimental cases. I will now add some README files with explanations and update the structure.

I think the error you were seeing in Simmons and Azzopardi case has to do with me using Polish characters in the title of the book.

I believe I also fixed the source relaxation. Ideally in an unsteady simulation you want this parameter to be 1.0 and this is what I set by default.

**Comment by frankyugit** [comment]
Hey, Robert,

Thanks for fixing the case, now the Simmons and Azzopardi case can be
successfully set up without any error.
After adding the relax factor to the `phaseProperties` I/O file, PBEFoam can
also successfully run on the case.
I'm now beginning to read the code you write and hope to contribute to this
case. After an overall reading, I got two questions maybe need your help
1st I found the design of PBEFoam solver is really a shock
-    while (runTime.run())    {        runTime++;        Info<< "Time = "
  << runTime.timeName() << nl << endl;        fluid.correct();
  runTime.write();        Info<< "ExecutionTime = "            <<
  runTime.elapsedCpuTime()            << " s\n\n" << endl;    }    Info<<
  "End\n" << endl;    return 0;*

In this part of code, the class, PBEMethod, has not really instantiated
here. So how we really realize the function of MOM, MOC, which are the
subclasses of PBEMethod. Could you explain a bit about the strategy behind
this code?

2nd Could you give me some tips on how to compile and run this case on IDEs
like Eclipse. I have tried the process given by the Youtube video _How to
use Eclipse as IDE for extending OpenFOAM_, however, when run the case,
this error still can be found
platforms/linux64GccDPInt32Opt/bin/PBEFoam: error while loading shared
libraries: libPstream.so: cannot open shared object file: No such file or
directory
What could be the possible error in eclipse configuration that can lead to
this problem, could you give me some tips?

Thanks a lot and look forward to your reply

Best Regards,
Frank

**Comment by robertsawko** [comment]
Hi Frank,

Can I ask you to raise questions on the gitter channel or over normal email? It's just a bit inconsistent that we're growing this Issue with irrelevant material. Github issues are meant to be a documentation of a kind so we should only keep them relevant.

Re your question one. The code is correct and this is one of the assumptions we followed: minimal intrusion into original code. This why `twoPhaseEulerFoam` works with PBE.

What we do is to add a diameter model. PBE is essentially a model for phase diameter from the `twoPhaseEulerFoam` perspective. The library a new run time selectible model `PBEDiameter` which has different methods for calculating it.

Sorry, I am not an Eclipse guru. I configured my project in an IDE agnostic way. There should be plenty of content on how to configure both OF and CMakeLists. I personally don't like Eclipse. Consider also other IDEs like QTCreator.
